version: "3"
services:
  #---------------------------------------
  # mysql database container
  #---------------------------------------
  mysqldb:
    # Set max_allowed_packet to 100M (or any other value)
    command: --max_allowed_packet=104857600 --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: ${COMPOSE_PROJECT_NAME}_mysqldb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    image: "mysql:5.7"
    networks:
      - net
    ports:
      - ${PORT_MYSQL}:3306
    restart: "no"
    volumes:
      - mysqldb_data:/var/lib/mysql

  #---------------------------------------
  # phpmyadmin container
  #---------------------------------------
  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: ${MYSQLDB_HOST}
      PMA_USER: ${MYSQLDB_ROOT_USER}
      PMA_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    image: phpmyadmin:5.2
    networks:
      - net
    ports:
      - "${PORT_PHPADMIN}:80"
    restart: "no"

networks:
  net:
volumes:
  mysqldb_data:
